###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    memcached:
        image: 'memcached:alpine'

    mariadb:
        container_name: "php-api-db"
        image: 'mariadb:10.10'
        working_dir: /app
        volumes:
            - '.:/app'
        environment:
            - MYSQL_ROOT_PASSWORD=123
            - MYSQL_DATABASE=php_api
            - MYSQL_USER=root
            - MYSQL_PASSWORD=123
        ports:
            - '3306:3306'
        networks:
              db_network:
                  ipv4_address: 192.168.151.51

    clickhouse:
        image: 'clickhouse/clickhouse-server:latest'

    webserver:
        container_name: "php-api-nginx"
        image: 'nginx:alpine'
        working_dir: /app
        volumes:
            - '.:/app'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8000:80'
        networks:
            db_network:
                ipv4_address: 192.168.151.52

    php-fpm:
        container_name: "php-api-fpm"
        build: phpdocker/php-fpm
        working_dir: /app
        ports:
            - '9000:9000'
        volumes:
            - '.:/app'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
        networks:
            db_network:
                ipv4_address: 192.168.151.53

networks:
    db_network:
        ipam:
            driver: default
            config:
                - subnet: 192.168.151.0/24